__name__ = 'Baby'
__type__ = 'class_type'

[__init__]
__name__ = '__init__'
__type__ = 'function_type'

    [__init__.__args__]
    co_argcount = 3
    co_cellvars = []
    co_code = [ 116, 0, 160, 1, 124, 0, 124, 2, 161, 2, 1, 0, 124, 1, 124, 0, 95, 2, 100, 0, 83, 0 ]
    co_consts = [ 'None' ]
    co_filename = '/home/pechenkovkysnoe/PycharmProjects/python/lab2_first/tests/test_things.py'
    co_firstlineno = 44
    co_flags = 67
    co_freevars = []
    co_kwonlyargcount = 0
    co_lnotab = [ 0, 1, 12, 1 ]
    co_name = '__init__'
    co_names = [ 'Dad', '__init__', 'first_name' ]
    co_nlocals = 3
    co_posonlyargcount = 0
    co_stacksize = 4
    co_varnames = [ 'self', 'first_name', 'second_name' ]

    [__init__.__globals__.Dad]
    __name__ = 'Dad'
    __type__ = 'class_type'

        [__init__.__globals__.Dad.__init__]
        __name__ = '__init__'
        __type__ = 'function_type'

            [__init__.__globals__.Dad.__init__.__args__]
            co_argcount = 2
            co_cellvars = []
            co_code = [ 124, 1, 124, 0, 95, 0, 100, 0, 83, 0 ]
            co_consts = [ 'None' ]
            co_filename = '/home/pechenkovkysnoe/PycharmProjects/python/lab2_first/tests/test_things.py'
            co_firstlineno = 39
            co_flags = 67
            co_freevars = []
            co_kwonlyargcount = 0
            co_lnotab = [ 0, 1 ]
            co_name = '__init__'
            co_names = [ 'second_name' ]
            co_nlocals = 2
            co_posonlyargcount = 0
            co_stacksize = 2
            co_varnames = [ 'self', 'second_name' ]

            [__init__.__globals__.Dad.__init__.__globals__]

[get_full_name]
__name__ = 'get_full_name'
__type__ = 'function_type'

    [get_full_name.__args__]
    co_argcount = 1
    co_cellvars = []
    co_code = [ 124, 0, 106, 0, 124, 0, 106, 1, 103, 2, 83, 0 ]
    co_consts = [ 'None' ]
    co_filename = '/home/pechenkovkysnoe/PycharmProjects/python/lab2_first/tests/test_things.py'
    co_firstlineno = 48
    co_flags = 67
    co_freevars = []
    co_kwonlyargcount = 0
    co_lnotab = [ 0, 1 ]
    co_name = 'get_full_name'
    co_names = [ 'first_name', 'second_name' ]
    co_nlocals = 1
    co_posonlyargcount = 0
    co_stacksize = 2
    co_varnames = [ 'self' ]

    [get_full_name.__globals__]