# Generated by Django 4.0.4 on 2022-05-22 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 20, 44, 14, 92397, tzinfo=utc), verbose_name='Дата атрымання замовы'),
        ),
    ]
