# Generated by Django 4.0.4 on 2022-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_customer', to='mainapp.order', verbose_name='Заказы покупателя'),
        ),
    ]
