# Generated by Django 4.0.4 on 2022-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_short_longshort_dress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longshort',
            name='belt_length',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина пояса'),
        ),
    ]
