# Generated by Django 4.0.4 on 2022-05-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_longshort_belt_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longshort',
            name='belt',
        ),
    ]
