# Generated by Django 4.0.4 on 2022-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_longshort_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longshort',
            name='belt_length',
            field=models.CharField(default=0, max_length=255, verbose_name='Длина пояса'),
        ),
    ]
