# Generated by Django 4.0.4 on 2022-05-18 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_longshort_belt_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрас'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Самавываз'), ('delivery', 'Дастаўка')], default='self', max_length=255, verbose_name='Тып замовы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Кошык'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Каментарый да заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_ad',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата стварэння замовы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пакупнік'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Імя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата атрымання замовы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Тэлефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='Прозвішча'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая замова'), ('in_progress', 'Замова ў апрацоўцы'), ('is_ready', 'Замова гатовы'), ('completed', 'Замова выкананы')], default='new', max_length=255, verbose_name='Статус замовы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='third_name',
            field=models.CharField(max_length=255, verbose_name='Імя па бацьку'),
        ),
    ]
