# Generated by Django 4.0.4 on 2022-05-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_order_address_alter_order_buying_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
