# Generated by Django 4.0.4 on 2022-05-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_customer_address_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
