# Generated by Django 4.0.4 on 2022-05-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_smartphone_category_delete_notebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_ad',
        ),
    ]
