version: "3.0"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=compose_second
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD='password'
      - POSTGRES_HOST=db
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=compose_second
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD='password'
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL='redis://redis:6379/0'
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A lab3 worker -l info
    volumes:
      - ./pdf_generator/:/usr/src/pdf_generator/
    environment:
      - DB_HOST=db
      - DB_NAME=compose_second
      - DB_USER=postgres
      - DB_PASS='password'
    depends_on:
      - redis

volumes:
  redis_data: